### ISSUE TITLE
Mini PR

### ISSUE THREAD

**Issue by eddelbuettel** [pcaspers/Quantuccia#6]
I have a trivial PR for you which suppressing a compiler warning; same fix had been made in QL itself too.

We had some, errr, "repeated difficulties" merging simple pull requests.  I don't think I had such issues with other repos I have contributed too.  (And in fairness I think for one of these I accidentally committed extra files.)   Is there a special procedure you require or shall I just PR from my fork?

**Comment by pcaspers** [comment]
The only thing I am concerned about is this commit bc94c62bb61b34dce69 with the binary in it, which (I think) would become part of my history when I merge from your fork. But send your PR anyway, I can just cherry pick the relevant commits.

**Comment by eddelbuettel** [comment]
You misunderstand.  I have a clean fork from you, see [here](https://github.com/eddelbuettel/Quantuccia). It is bit to bit identical to your repo.   So no chance that can happen.

I fear you may also misunderstand relation ships between distinct PRs _i_ and _j_.   Content of _i_ is orthogonal to _j_ (provided they branched at different points off master),   That is the whole point of version control.

**Comment by pcaspers** [comment]
Thanks Dirk, that's great. Then send the PR from the clean fork.
